### ISSUE TITLE
sdk.Lists.registerComposeViewHandler either doesn't work, or is erroneously in the docs

### ISSUE THREAD

**Issue by alexeacott-tech** [InboxSDK/inboxsdk-docs#19]
In the lists namespace, it says you can register a composeViewHandler, which is preferable to in the Compose namespace. However invoking sdk.Lists.registerComposeViewHandler results in `sdk.Lists.registerComposeViewHandler is not a function`

**Comment by aleemstreak** [comment]
fixed, thanks for the report!
