### ISSUE TITLE
Website search broken

### ISSUE THREAD

**Issue by wegry** [InboxSDK/inboxsdk-docs#26]
**Describe the bug**

The documentation site Algolia search appears to be broken. When searching for 'MessageView', I see no results and a lot of errors in the browser console. One example:

```
https://inboxsdk-dsn.algolia.net/1/indexes/*/queries?x-algolia-agent=Algolia%20for%20JavaScript%20(4.14.2)%3B%20Browser%20(lite)%3B%20docsearch%20(3.2.1)%3B%20docsearch-react%20(3.2.1)%3B%20docusaurus%20(2.1.0)&x-algolia-api-key=319308999ead35d0a17df976af4a951a&x-algolia-application-id=inboxsdk
Failed to load resource: A server with the specified hostname could not be found.
```

**Expected behavior**

Algolia successfully returns the 'MessageView' page when searching for 'MessageView'

**Screenshots**

<img width="1512" alt="Screenshot 2023-08-07 at 15 34 18" src="https://github.com/InboxSDK/inboxsdk-docs/assets/5156873/b146485d-05a1-4488-955d-73cb2f712525">

<img width="1456" alt="Screenshot 2023-08-07 at 15 31 56" src="https://github.com/InboxSDK/inboxsdk-docs/assets/5156873/596e3e59-a045-4217-81a9-b99197d6d0a2">

**Comment by wegry** [comment]
@Macil please create a new issue without me tagged if you're still interested in this.

**Comment by Macil** [comment]
I've disabled the broken search feature for now.
